# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nilas\Documents\maya\2019\scripts\nc_soundeness_checker\ncsc_ui/soundness_checker_ui.ui'
#
# Created: Fri Feb 21 13:01:36 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SoundnessChecker(object):
    def setupUi(self, SoundnessChecker):
        SoundnessChecker.setObjectName("SoundnessChecker")
        SoundnessChecker.resize(403, 621)
        self.gridLayout_2 = QtWidgets.QGridLayout(SoundnessChecker)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(SoundnessChecker)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 346, 640))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.geo_grpbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.geo_grpbox.setObjectName("geo_grpbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.geo_grpbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.del_hist_layout = QtWidgets.QHBoxLayout()
        self.del_hist_layout.setObjectName("del_hist_layout")
        self.dh_lbl = QtWidgets.QLabel(self.geo_grpbox)
        self.dh_lbl.setObjectName("dh_lbl")
        self.del_hist_layout.addWidget(self.dh_lbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.del_hist_layout.addItem(spacerItem)
        self.dh_fix_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.dh_fix_btn.setObjectName("dh_fix_btn")
        self.del_hist_layout.addWidget(self.dh_fix_btn)
        self.verticalLayout.addLayout(self.del_hist_layout)
        self.get_borders_layout = QtWidgets.QHBoxLayout()
        self.get_borders_layout.setObjectName("get_borders_layout")
        self.gb_lbl = QtWidgets.QLabel(self.geo_grpbox)
        self.gb_lbl.setObjectName("gb_lbl")
        self.get_borders_layout.addWidget(self.gb_lbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.get_borders_layout.addItem(spacerItem1)
        self.gb_fix_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.gb_fix_btn.setObjectName("gb_fix_btn")
        self.get_borders_layout.addWidget(self.gb_fix_btn)
        self.gb_show_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.gb_show_btn.setObjectName("gb_show_btn")
        self.get_borders_layout.addWidget(self.gb_show_btn)
        self.verticalLayout.addLayout(self.get_borders_layout)
        self.more_than_four_layout = QtWidgets.QHBoxLayout()
        self.more_than_four_layout.setObjectName("more_than_four_layout")
        self.mtf_lbl = QtWidgets.QLabel(self.geo_grpbox)
        self.mtf_lbl.setObjectName("mtf_lbl")
        self.more_than_four_layout.addWidget(self.mtf_lbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.more_than_four_layout.addItem(spacerItem2)
        self.mtf_fix_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.mtf_fix_btn.setObjectName("mtf_fix_btn")
        self.more_than_four_layout.addWidget(self.mtf_fix_btn)
        self.mtf_show_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.mtf_show_btn.setObjectName("mtf_show_btn")
        self.more_than_four_layout.addWidget(self.mtf_show_btn)
        self.verticalLayout.addLayout(self.more_than_four_layout)
        self.normal_direction_layout = QtWidgets.QHBoxLayout()
        self.normal_direction_layout.setObjectName("normal_direction_layout")
        self.nd_lbl = QtWidgets.QLabel(self.geo_grpbox)
        self.nd_lbl.setObjectName("nd_lbl")
        self.normal_direction_layout.addWidget(self.nd_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.normal_direction_layout.addItem(spacerItem3)
        self.nd_fix_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.nd_fix_btn.setObjectName("nd_fix_btn")
        self.normal_direction_layout.addWidget(self.nd_fix_btn)
        self.nd_show_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.nd_show_btn.setObjectName("nd_show_btn")
        self.normal_direction_layout.addWidget(self.nd_show_btn)
        self.verticalLayout.addLayout(self.normal_direction_layout)
        self.non_manifold_layout = QtWidgets.QHBoxLayout()
        self.non_manifold_layout.setObjectName("non_manifold_layout")
        self.nm_lbl = QtWidgets.QLabel(self.geo_grpbox)
        self.nm_lbl.setObjectName("nm_lbl")
        self.non_manifold_layout.addWidget(self.nm_lbl)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.non_manifold_layout.addItem(spacerItem4)
        self.nm_fix_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.nm_fix_btn.setObjectName("nm_fix_btn")
        self.non_manifold_layout.addWidget(self.nm_fix_btn)
        self.nm_show_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.nm_show_btn.setObjectName("nm_show_btn")
        self.non_manifold_layout.addWidget(self.nm_show_btn)
        self.verticalLayout.addLayout(self.non_manifold_layout)
        self.lamina_faces_layout = QtWidgets.QHBoxLayout()
        self.lamina_faces_layout.setObjectName("lamina_faces_layout")
        self.lf_lbl = QtWidgets.QLabel(self.geo_grpbox)
        self.lf_lbl.setObjectName("lf_lbl")
        self.lamina_faces_layout.addWidget(self.lf_lbl)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lamina_faces_layout.addItem(spacerItem5)
        self.lf_fix_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.lf_fix_btn.setObjectName("lf_fix_btn")
        self.lamina_faces_layout.addWidget(self.lf_fix_btn)
        self.lf_show_btn = QtWidgets.QPushButton(self.geo_grpbox)
        self.lf_show_btn.setObjectName("lf_show_btn")
        self.lamina_faces_layout.addWidget(self.lf_show_btn)
        self.verticalLayout.addLayout(self.lamina_faces_layout)
        self.verticalLayout_5.addWidget(self.geo_grpbox)
        self.naming_grpbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.naming_grpbox.setObjectName("naming_grpbox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.naming_grpbox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.check_suffix_layout = QtWidgets.QHBoxLayout()
        self.check_suffix_layout.setObjectName("check_suffix_layout")
        self.cs_lbl = QtWidgets.QLabel(self.naming_grpbox)
        self.cs_lbl.setObjectName("cs_lbl")
        self.check_suffix_layout.addWidget(self.cs_lbl)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.check_suffix_layout.addItem(spacerItem6)
        self.cs_fix_btn = QtWidgets.QPushButton(self.naming_grpbox)
        self.cs_fix_btn.setObjectName("cs_fix_btn")
        self.check_suffix_layout.addWidget(self.cs_fix_btn)
        self.verticalLayout_7.addLayout(self.check_suffix_layout)
        self.check_materials_layout = QtWidgets.QHBoxLayout()
        self.check_materials_layout.setObjectName("check_materials_layout")
        self.cm_lbl = QtWidgets.QLabel(self.naming_grpbox)
        self.cm_lbl.setObjectName("cm_lbl")
        self.check_materials_layout.addWidget(self.cm_lbl)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.check_materials_layout.addItem(spacerItem7)
        self.cm_fix_btn = QtWidgets.QPushButton(self.naming_grpbox)
        self.cm_fix_btn.setObjectName("cm_fix_btn")
        self.check_materials_layout.addWidget(self.cm_fix_btn)
        self.verticalLayout_7.addLayout(self.check_materials_layout)
        self.letter_padding_layout = QtWidgets.QHBoxLayout()
        self.letter_padding_layout.setObjectName("letter_padding_layout")
        self.lp_lbl = QtWidgets.QLabel(self.naming_grpbox)
        self.lp_lbl.setObjectName("lp_lbl")
        self.letter_padding_layout.addWidget(self.lp_lbl)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.letter_padding_layout.addItem(spacerItem8)
        self.lp_fix_btn = QtWidgets.QPushButton(self.naming_grpbox)
        self.lp_fix_btn.setObjectName("lp_fix_btn")
        self.letter_padding_layout.addWidget(self.lp_fix_btn)
        self.verticalLayout_7.addLayout(self.letter_padding_layout)
        self.verticalLayout_5.addWidget(self.naming_grpbox)
        self.transform_grpbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.transform_grpbox.setObjectName("transform_grpbox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.transform_grpbox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.place_top_node_layout = QtWidgets.QHBoxLayout()
        self.place_top_node_layout.setObjectName("place_top_node_layout")
        self.ptn_lbl = QtWidgets.QLabel(self.transform_grpbox)
        self.ptn_lbl.setObjectName("ptn_lbl")
        self.place_top_node_layout.addWidget(self.ptn_lbl)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.place_top_node_layout.addItem(spacerItem9)
        self.ptn_fix_btn = QtWidgets.QPushButton(self.transform_grpbox)
        self.ptn_fix_btn.setObjectName("ptn_fix_btn")
        self.place_top_node_layout.addWidget(self.ptn_fix_btn)
        self.verticalLayout_6.addLayout(self.place_top_node_layout)
        self.zero_pivot_layout = QtWidgets.QHBoxLayout()
        self.zero_pivot_layout.setObjectName("zero_pivot_layout")
        self.zp_lbl = QtWidgets.QLabel(self.transform_grpbox)
        self.zp_lbl.setObjectName("zp_lbl")
        self.zero_pivot_layout.addWidget(self.zp_lbl)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.zero_pivot_layout.addItem(spacerItem10)
        self.zp_fix_btn = QtWidgets.QPushButton(self.transform_grpbox)
        self.zp_fix_btn.setObjectName("zp_fix_btn")
        self.zero_pivot_layout.addWidget(self.zp_fix_btn)
        self.verticalLayout_6.addLayout(self.zero_pivot_layout)
        self.move_above_zero_layout = QtWidgets.QHBoxLayout()
        self.move_above_zero_layout.setObjectName("move_above_zero_layout")
        self.maz_lbl = QtWidgets.QLabel(self.transform_grpbox)
        self.maz_lbl.setObjectName("maz_lbl")
        self.move_above_zero_layout.addWidget(self.maz_lbl)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.move_above_zero_layout.addItem(spacerItem11)
        self.maz_fix_btn = QtWidgets.QPushButton(self.transform_grpbox)
        self.maz_fix_btn.setObjectName("maz_fix_btn")
        self.move_above_zero_layout.addWidget(self.maz_fix_btn)
        self.verticalLayout_6.addLayout(self.move_above_zero_layout)
        self.freeze_trans_layout = QtWidgets.QHBoxLayout()
        self.freeze_trans_layout.setObjectName("freeze_trans_layout")
        self.ft_lbl = QtWidgets.QLabel(self.transform_grpbox)
        self.ft_lbl.setObjectName("ft_lbl")
        self.freeze_trans_layout.addWidget(self.ft_lbl)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.freeze_trans_layout.addItem(spacerItem12)
        self.ft_fix_btn = QtWidgets.QPushButton(self.transform_grpbox)
        self.ft_fix_btn.setObjectName("ft_fix_btn")
        self.freeze_trans_layout.addWidget(self.ft_fix_btn)
        self.verticalLayout_6.addLayout(self.freeze_trans_layout)
        self.verticalLayout_5.addWidget(self.transform_grpbox)
        self.uv_grpbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.uv_grpbox.setObjectName("uv_grpbox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.uv_grpbox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.open_uv_seams_layout = QtWidgets.QHBoxLayout()
        self.open_uv_seams_layout.setObjectName("open_uv_seams_layout")
        self.ous_lbl = QtWidgets.QLabel(self.uv_grpbox)
        self.ous_lbl.setObjectName("ous_lbl")
        self.open_uv_seams_layout.addWidget(self.ous_lbl)
        self.ous_fix_btn = QtWidgets.QPushButton(self.uv_grpbox)
        self.ous_fix_btn.setObjectName("ous_fix_btn")
        self.open_uv_seams_layout.addWidget(self.ous_fix_btn)
        self.ous_show_btn = QtWidgets.QPushButton(self.uv_grpbox)
        self.ous_show_btn.setObjectName("ous_show_btn")
        self.open_uv_seams_layout.addWidget(self.ous_show_btn)
        self.verticalLayout_8.addLayout(self.open_uv_seams_layout)
        self.overlapping_uvs_layout = QtWidgets.QHBoxLayout()
        self.overlapping_uvs_layout.setObjectName("overlapping_uvs_layout")
        self.ou_lbl = QtWidgets.QLabel(self.uv_grpbox)
        self.ou_lbl.setObjectName("ou_lbl")
        self.overlapping_uvs_layout.addWidget(self.ou_lbl)
        self.ou_fix_btn = QtWidgets.QPushButton(self.uv_grpbox)
        self.ou_fix_btn.setObjectName("ou_fix_btn")
        self.overlapping_uvs_layout.addWidget(self.ou_fix_btn)
        self.ou_show_btn = QtWidgets.QPushButton(self.uv_grpbox)
        self.ou_show_btn.setObjectName("ou_show_btn")
        self.overlapping_uvs_layout.addWidget(self.ou_show_btn)
        self.verticalLayout_8.addLayout(self.overlapping_uvs_layout)
        self.inverted_uvs_layout = QtWidgets.QHBoxLayout()
        self.inverted_uvs_layout.setObjectName("inverted_uvs_layout")
        self.iu_lbl = QtWidgets.QLabel(self.uv_grpbox)
        self.iu_lbl.setObjectName("iu_lbl")
        self.inverted_uvs_layout.addWidget(self.iu_lbl)
        self.iu_fix_btn = QtWidgets.QPushButton(self.uv_grpbox)
        self.iu_fix_btn.setObjectName("iu_fix_btn")
        self.inverted_uvs_layout.addWidget(self.iu_fix_btn)
        self.iu_show_btn = QtWidgets.QPushButton(self.uv_grpbox)
        self.iu_show_btn.setObjectName("iu_show_btn")
        self.inverted_uvs_layout.addWidget(self.iu_show_btn)
        self.verticalLayout_8.addLayout(self.inverted_uvs_layout)
        self.verticalLayout_5.addWidget(self.uv_grpbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(SoundnessChecker)
        QtCore.QMetaObject.connectSlotsByName(SoundnessChecker)

    def retranslateUi(self, SoundnessChecker):
        SoundnessChecker.setWindowTitle(QtWidgets.QApplication.translate("SoundnessChecker", "Dialog", None, -1))
        self.geo_grpbox.setTitle(QtWidgets.QApplication.translate("SoundnessChecker", "Geometry", None, -1))
        self.dh_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Delete the history on all or selected objects", None, -1))
        self.dh_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Delete History", None, -1))
        self.dh_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.gb_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Select borders on all or selected objects", None, -1))
        self.gb_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Get Borders", None, -1))
        self.gb_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.gb_show_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Show", None, -1))
        self.mtf_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Checks for polys with more than four sides", None, -1))
        self.mtf_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "More Than Four", None, -1))
        self.mtf_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.mtf_show_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Show", None, -1))
        self.nd_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Select the normals that are turning the \"wrong\" way", None, -1))
        self.nd_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Normal Direction", None, -1))
        self.nd_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.nd_show_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Show", None, -1))
        self.nm_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Check for non manifold geometry", None, -1))
        self.nm_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Non Manifold", None, -1))
        self.nm_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.nm_show_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Show", None, -1))
        self.lf_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Check for lamina faces", None, -1))
        self.lf_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Lamina Faces", None, -1))
        self.lf_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.lf_show_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Show", None, -1))
        self.naming_grpbox.setTitle(QtWidgets.QApplication.translate("SoundnessChecker", "Naming", None, -1))
        self.cs_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Check that objects have appropriate suffix. e.g. \"_grp\" and \"_geo\"", None, -1))
        self.cs_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Suffix", None, -1))
        self.cs_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.cm_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Check that material nodes are named correctly", None, -1))
        self.cm_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Materials", None, -1))
        self.cm_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.lp_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Check for letter padding on eveything in the outliner", None, -1))
        self.lp_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Letter Padding", None, -1))
        self.lp_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.transform_grpbox.setTitle(QtWidgets.QApplication.translate("SoundnessChecker", "Transform", None, -1))
        self.ptn_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Places a top node for all geometry in the scene.", None, -1))
        self.ptn_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Place Top Node", None, -1))
        self.ptn_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.zp_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Places the node pivot in world 0, 0, 0", None, -1))
        self.zp_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Zero Pivot", None, -1))
        self.zp_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.maz_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Move geometry above -0.005", None, -1))
        self.maz_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Move Above Zero", None, -1))
        self.maz_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.ft_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Freeze transforms", None, -1))
        self.ft_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Freeze Transforms", None, -1))
        self.ft_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.uv_grpbox.setTitle(QtWidgets.QApplication.translate("SoundnessChecker", "UV", None, -1))
        self.ous_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Checks for open UV seams", None, -1))
        self.ous_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Open UV Seams", None, -1))
        self.ous_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.ous_show_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Show", None, -1))
        self.ou_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Checks if any of the UV\'s are overlapping", None, -1))
        self.ou_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Overlapping UV\'s", None, -1))
        self.ou_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.ou_show_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Show", None, -1))
        self.iu_lbl.setToolTip(QtWidgets.QApplication.translate("SoundnessChecker", "Checks for inverted UV\'s", None, -1))
        self.iu_lbl.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Inverted UV\'s", None, -1))
        self.iu_fix_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Fix", None, -1))
        self.iu_show_btn.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Show", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("SoundnessChecker", "Select All Geometry in Scene", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("SoundnessChecker", "Select All Geomtry", None, -1))

